# Generated by Django 4.1.7 on 2023-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_t_app', '0002_joke'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='age_appropriate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='joke',
            name='flag_offensive',
            field=models.BooleanField(default=False),
        ),
    ]
